export const GH_GEOLOCATION = {
    latitude: 8.030028399390375,
    longitude: -1.0800271,
    countryName: 'Ghana'
}

export const regionalGeoCodes = [
    {
        regionName: 'Ahafo Region',
        longitude: -2.5350966,
        latitude: 6.916885199407648
    },
    {
        regionName: 'Ashanti Region',
        longitude: -1.5188142,
        latitude: 6.800331899411259
    },
    {
        regionName: 'Bono East Region',
        longitude: -1.0876492,
        latitude: 7.803523599391317
    },
    {
        regionName: 'Bono Region',
        longitude: -2.4735401,
        latitude: 7.67617909939243
    },
    {
        regionName: 'Central Region',
        longitude: 	-1.3761748999999999,
        latitude: 5.724414799459805
    },
    {
        regionName: 'Eastern Region',
        longitude: -0.3770964,
        latitude: 	6.44687699942423
    },
    {
        regionName: 'Greater Accra Region',
        longitude: 0.09952419999999998,
        latitude: 5.810153199454975
    },
    {
        regionName: 'North East Region',
        longitude: -0.5410794,
        latitude: 10.395977299459267
    },
    {
        regionName: 'Northern Region',
        longitude: 	-0.39437989999999995,
        latitude: 	9.66000049942276
    },
    {
        regionName: 'Oti Region',
        longitude: 	0.318598,
        latitude: 7.86338719939094
    },
    {
        regionName: 'Savannah Region',
        longitude: -1.7111234,
        latitude: 9.140065399405014
    },
    {
        regionName: 'Upper East Region',
        longitude: -0.690011502573924,
        latitude: 	10.804648633598731
    },
    {
        regionName: 'Upper West Region',
        longitude: -2.0921426,
        latitude: 	10.366952499457586
    },
    {
        regionName: 'Volta Region',
        longitude: 0.4556055,
        latitude: 6.534862399420721
    },
    {
        regionName: 'Western North Region',
        longitude: 	-2.8234891,
        latitude: 	6.227936699433756
    },
    {
        regionName: 'Western Region',
        longitude: 	-2.1286573999999994,
        latitude: 	5.426124099477842
    },
]

export const districtsByRegion = {
    "Western Region": [
      "Jomoro Municipal",
      "Ellembelle",
      "Nzema East Municipal",
      "Ahanta West Municipal",
      "Effia Kwesimintsim Municipal",
      "Sekondi Takoradi Metropolitan Area (STM)",
      "Shama",
      "Wassa East",
      "Mpohor",
      "Tarkwa-Nsuaem Municipal",
      "Prestea/Huni Valley Municipal",
      "Wassa Amenfi East Municipal",
      "Wassa Amenfi Central",
      "Wassa Amenfi West Municipal"
    ],
    "Central Region": [
      "Komenda Edina Eguafo Abirem Municipal",
      "Cape Coast Metropolitan Area (CCMA)",
      "Abura Asebu Kwamankese",
      "Mfantsiman Municipal",
      "Ekumfi",
      "Gomoa West",
      "Effutu Municipal",
      "Gomoa Central",
      "Gomoa East",
      "Awutu Senya East Municipal",
      "Awutu Senya",
      "Agona East",
      "Agona West Municipal",
      "Asikuma Odoben Brakwa",
      "Ajumako Enyan Essiam",
      "Assin South",
      "Twifo Heman Lower Denkyira",
      "Twifo Ati Morkwa",
      "Assin Fosu Municipal",
      "Assin North",
      "Upper Denkyira East Municipal",
      "Upper Denkyira West"
    ],
    "Greater Accra Region": [
      "Ga South Municipal",
      "Weija Gbawe Municipal",
      "Ga Central Municipal",
      "Ablekuma North Municipal",
      "Ablekuma West Municipal",
      "Ablekuma Central Municipal",
      "Accra Metropolitan Area (AMA)",
      "Korle Klottey Municipal",
      "Ayawaso Central Municipal",
      "Ayawaso East Municipal",
      "Ayawaso North Municipal",
      "La Dade-Kotopon Municipal",
      "Ledzokuku Municipal",
      "Krowor Municipal",
      "Adentan Municipal",
      "Ayawaso West Municipal",
      "Okaikoi North Municipal",
      "Ga North Municipal",
      "Ga West Municipal",
      "Ga East Municipal",
      "La Nkwantanang Madina Municipal",
      "Kpone Katamanso Municipal",
      "Ashaiman Municipal",
      "Tema West Municipal",
      "Tema Metropolitan Area (TMA)",
      "Ningo-Prampram",
      "Shai-Osudoku",
      "Ada West",
      "Ada East"
    ],
    "Volta Region": [
      "South Tongu",
      "Anloga",
      "Keta Municipal",
      "Ketu South Municipal",
      "Ketu North Municipal",
      "Akatsi North",
      "Akatsi South Municipal",
      "Central Tongu",
      "North Tongu",
      "Ho West",
      "Adaklu",
      "Agortime-Ziope",
      "Ho Municipal",
      "South Dayi",
      "Afadzato South",
      "North Dayi",
      "Kpando Municipal",
      "Hohoe Municipal"
    ],
    "Eastern Region": [
      "Birim South",
      "Birim Central Municipal",
      "Achiase",
      "Asene Manso Akroso",
      "West Akim Municipal",
      "Upper West Akim",
      "Ayensuano",
      "Nsawam Adoagyiri Municipal",
      "Akwapim South Municipal",
      "Akwapim North Municipal",
      "Okere",
      "New Juaben South Municipal",
      "New Juaben North Municipal",
      "Suhum Municipal",
      "Abuakwa North Municipal",
      "Abuakwa South Municipal",
      "Denkyembuor",
      "Akyemansa",
      "Kwaebibirem Municipal",
      "Birim North",
      "Atiwa West",
      "Atiwa East",
      "Fanteakwa South",
      "Yilo Krobo Municipal",
      "Lower Manya Krobo Municipal",
      "Asuogyaman",
      "Upper Manya Krobo",
      "Fanteakwa North",
      "Kwahu South Municipal",
      "Kwahu West Municipal",
      "Kwahu East",
      "Kwahu Afram Plains South",
      "Kwahu Afram Plains North"
    ],
    "Ashanti Region": [
      "Amansie South",
      "Amansie Central",
      "Akrofuom",
      "Adansi South",
      "Adansi Asokwa",
      "Obuasi East",
      "Obuasi Municipal",
      "Adansi North",
      "Bekwai Municipal",
      "Amansie West",
      "Atwima Kwanwoma",
      "Bosomtwi",
      "Bosome Freho",
      "Asante Akim Central Municipal",
      "Asante Akim South Municipal",
      "Asante Akim North Municipal",
      "Sekyere Kumawu",
      "Sekyere East",
      "Juaben Municipal",
      "Ejisu Municipal",
      "Oforikrom Municipal",
      "Asokwa Municipal",
      "Kumasi Metropolitan Area (KMA)",
      "Kwadaso Municipal",
      "Suame Municipal",
      "Old Tafo Municipal",
      "Asokore Mampong Municipal",
      "Kwabre East",
      "Afigya Kwabre South",
      "Atwima Nwabiagya North",
      "Atwima Nwabiagya South Municipal",
      "Atwima Mponua",
      "Ahafo Ano South West",
      "Ahafo Ano North Municipal",
      "Ahafo Ano South East",
      "Offinso North",
      "Offinso Municipal",
      "Afigya Kwabre North",
      "Sekyere South",
      "Mampong Municipal",
      "Ejura Sekyedumase Municipal",
      "Sekyere Central",
      "Sekyere Afram Plains"
    ],
    "Western North Region": [
      "Aowin Municipal",
      "Sefwi Akontombra",
      "Suaman",
      "Bodi",
      "Sefwi Wiawso Municipal",
      "Bibiani Anhwiaso Bekwai Municipal",
      "Juaboso",
      "Bia West",
      "Bia East"
    ],
    "Ahafo Region": [
      "Asunafo South",
      "Asunafo North Municipal",
      "Asutifi South",
      "Asutifi North",
      "Tano North Municipal",
      "Tano South Municipal"
    ],
    "Bono Region": [
      "Dormaa West",
      "Dormaa Central Municipal",
      "Dormaa East",
      "Sunyani Municipal",
      "Sunyani West Municipal",
      "Berekum East Municipal",
      "Berekum West",
      "Jaman South",
      "Jaman North",
      "Tain",
      "Wenchi Municipal",
      "Banda"
    ],
    "Bono East Region": [
      "Nkoranza South Municipal",
      "Techiman Municipal",
      "Nkoranza North",
      "Techiman North",
      "Atebubu Amantin Municipal",
      "Sene West",
      "Sene East",
      "Pru West",
      "Pru East",
      "Kintampo South",
      "Kintampo North Municipal"
    ],
    "Oti Region": [
      "Biakoye",
      "Jasikan Municipal",
      "Kadjebi",
      "Krachi East Municipal",
      "Krachi West Municipal",
      "Krachi Nchumuru",
      "Nkwanta South Municipal",
      "Nkwanta North (Kpassa)",
      "Guan"
    ],
    "Northern Region": [
      "Kpandai",
      "Nanumba South",
      "Nanumba North Municipal",
      "Zabzugu",
      "Tatale Sanguli",
      "Saboba",
      "Yendi Municipal",
      "Mion",
      "Nanton",
      "Tamale Metropolitan Area (TMA)",
      "Sagnarigu Municipal",
      "Tolon",
      "Kumbungu",
      "Savelugu Municipal",
      "Karaga",
      "Gushegu Municipal"
    ],
    "Savannah Region": [
      "Bole",
      "Sawla Tuna Kalba",
      "North Gonja",
      "West Gonja",
      "Central Gonja",
      "East Gonja Municipal",
      "North East Gonja"
    ],
    "North East Region": [
      "Mamprugu Moagduri",
      "West Mamprusi Municipal",
      "East Mamprusi Municipal",
      "Bunkpurugu Nakpanduri",
      "Yunyoo Nasuan",
      "Chereponi"
    ],
    "Upper East Region": [
      "Builsa South",
      "Builsa North Municipal",
      "Kasena Nankana Municipal",
      "Kasena Nankana West",
      "Bolgatanga Municipal",
      "Talensi",
      "Bolgatanga East",
      "Bongo",
      "Nabdam",
      "Bawku West",
      "Binduri",
      "Bawku Municipal",
      "Garu",
      "Tempane",
      "Pusiga"
    ],
    "Upper West Region": [
      "Wa West",
      "Wa East",
      "Wa Municipal",
      "Nadowli Kaleo",
      "Daffiama Bussie Issa",
      "Sissala East Municipal",
      "Sissala West",
      "Lambussie"
    ]
  };  